# Generated by Django 2.1.2 on 2018-10-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Mobile_Number', models.IntegerField()),
                ('Subject', models.CharField(max_length=20)),
                ('Your_message', models.CharField(max_length=20)),
            ],
        ),
    ]
